### ISSUE TITLE
There is a problem with multiple screens on Ubuntu 18.04

### ISSUE THREAD

**Issue by mvehar** [dandansoysauce/pall#3]
For external screen values are either #00000 or something random.

**Comment by dandansoysauce** [comment]
I will investigate this one.

**Comment by dandansoysauce** [comment]
Hi @mvehar, sorry for not updating the app, but I have an update that fixes this problem :)

**Comment by dandansoysauce** [comment]
Can you try the new version, @mvehar ? Are you on windows or linux?

**Comment by mvehar** [comment]
Hi @dandansoysauce , Im not working on Ubuntu at the moment.  I hope someone else can confirm that it's working.
