### ISSUE TITLE
This isn't a issue

### ISSUE THREAD

**Issue by TitanHero** [dandansoysauce/pall#4]
Regards, this isn't a issue your app is very cool, and works really fine, but  I just want advice you, that the app has a misspelling in a part of principal text  in the path /src/renderer/index.js  in the line 184, you write bye instead buy, for me this isn't important, because your app works very well and I'm the mundial king of the misspelling even one time I wrote bad misspelling(true history) but maybe for you it is important, and it is all, I hope be helpful.
![captura de pantalla_2019-02-25_04-07-47](https://user-images.githubusercontent.com/18335094/53330491-37073a00-38b4-11e9-9f20-96d0c6d12316.png)

**Comment by dandansoysauce** [comment]
Wow, I didn't see this one. That's embarrassing. Will update it, thanks!

**Comment by dandansoysauce** [comment]
Released 2.0.2 to get this embarrassing typo off the app lol
